
services:
  app:
    build: .
    container_name: pustaka_app
    working_dir: /var/www/html
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    volumes:
      - ./:/var/www/html
    ports:
      - "9080:9000"
      - "8088:8088"
    depends_on:
      - mysql
    networks:
      - pustaka

  node:
    image: node:22
    container_name: node_pustaka
    working_dir: /var/www/html
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    networks:
      - pustaka
    command: tail -f /dev/null  # biar container node tetap hidup dan bisa exec manual

  webserver:
    image: nginx:alpine
    container_name: nginx_pustaka
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - pustaka

  mysql:
    image: mysql:8.0
    container_name: mysql_pustaka
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: e-pustaka
      MYSQL_USER: e-pustaka
      MYSQL_PASSWORD: e-pustaka
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pustaka
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_pustaka
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_pustaka   # Sesuai nama service MySQL
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - pustaka

networks:
  pustaka:

volumes:
  mysql_data: